spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_workout_tracker_db
    username: root
    password: Kecske69!

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never